### ISSUE TITLE
Problems compiling invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

### ISSUE THREAD

**Issue by jBachalo** [osiloke/ofxHeadCount#1]
Get the following on compile
OS 10.11.6 El Capitan, XCode 7.3.1

clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

**Comment by jBachalo** [comment]
Solved- targeting older os in Build Settings

**Comment by osiloke** [comment]
cool
